# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_rair_wrappers", use_symbols = TRUE, package_name = "rair")

#' @usage NULL
#' @useDynLib rair, .registration = TRUE
NULL

format_file_ <- function(path) .Call(wrap__format_file_, path)

format_code_ <- function(code) .Call(wrap__format_code_, code)


# nolint end
